#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd


while IFS=: read -r user _ uid _ _ home _
 do
    echo "Username: $user"
    echo "User ID: $uid"
    echo "Home directory: $home"
done < /etc/passwd
