#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.


while IFS=: read -r user pass uid gid info home shell; do
    echo "The user $user is part of the $gid gang, lives in $home and rides $shell. User ID's place is protected by the passcode $pass, more info about the user here: $uid $info"
done < /etc/passwd
