#!/usr/bin/env bash
#Bash script that displays the visitor IP along with the HTTP status code from the Apache log file


# Replace the path below with the path to your Apache log file
log_file="Users/mac/logs/apache-access.log"

# Use awk to extract the visitor IP and HTTP status code from the log file
awk '{print $1, $9}' "$log_file"
