#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes

hour=0
minute=1

while [ $hour -le 12 ] 
do
   while [ $minute -le 59 ]
   do
       echo "$hour:$(printf "%02d" $minute)"
       minute=$((minute + 1))
   done
   hour=$((hour + 1))
   minute=1
done
